version: "3.9"

volumes:
  config:
  files:
  mysql_config:
  mysql_data:
  mysql_key:
  mysql_password:
  nginx_etc:
  redis_data:
    
networks:
  default:
    attachable: true

services:
  #nginx setup
  web:
    image: nginx
    volumes:
      - type: bind
        source: ./nginx/html
        target: /usr/share/nginx/html
      - nginx_etc:/etc
      - files:/data
      - type: bind
        source: ./developer/web/assets
        target: /app/assets
    depends_on:
      - api_sails
   #/nginx

  #db: use Maria DB as our backend DB
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /secret/password
    volumes:
      - mysql_config:/etc/mysql/conf.d
      - mysql_data:/var/lib/mysql
      - mysql_key:/key
      - mysql_password:/secret
    # on windows: use this command. (be sure to clear out mysql/data folder)
    # command: mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON --wait-timeout=60 --interactive-timeout=60
    ######
    # when there is a problem with : Error: ER_CRASHED_ON_USAGE: Table 'AAAAAA' is marked as crashed and should be repaired
    # this can happen with the alter table algorithm: try the safest(and slowest) COPY
    command: ["mysqld", "--alter-algorithm=copy" , "--wait-timeout=60", "--interactive-timeout=60"]
  #/db


  #redis: use redis to allow cote services to find each other across a swarm
  redis:
    image: redis
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
  #/redis


  #config: simply exists to pull in the config/local.js into our config volume
  config:
    image: node
    # environment:
    #   - AB_CONFIG_INSTALL=true
    volumes:
      - type: bind
        source: ./developer/config
        target: /app
      - type: bind
        source: ./config/local.js
        target: /config_safe/local.js
      - config:/config
    working_dir: /app
    command: ["node", "app.js"]
  #/config


  #api_sails: our API end point
  api_sails:
    image: node
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
    volumes:
      - type: bind
        source: ./logs/appbuilder/
        target: /var/log/appbuilder/
      - type: bind
        source: ./developer/api_sails
        target: /app
      - config:/app/config
      - files:/data
    depends_on:
      - redis
      - config
    working_dir: /app
    command: [ "node", "--inspect=0.0.0.0:9229", "app_waitMysql.js" ]
  #/api_sails


  #appbuilder: (AppBuilder) A multi-tenant aware service to process our AppBuilder requests.
  appbuilder:
    image: node
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
    volumes:
      - type: bind
        source: ./developer/appbuilder
        target: /app
      - config:/app/config
    depends_on:
      - redis
      - config
    working_dir: /app
    # command: npm run dev  # <-- runs nodemon and auto starts when code changes
    command: [ "node", "--inspect=0.0.0.0:9229", "app.js" ]
  #/appbuilder


  #bot_manager: our #slack bot service
  bot_manager:
    image: node
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
    volumes:
      - type: bind
        source: ./developer/bot_manager
        target: /app
      - config:/app/config
      # sharing .sock files currently don't work on docker-for-mac:
      # https://github.com/docker/for-mac/issues/483
      # For a Mac host, configure config/local.js to hostConnection.tcp
      # but it doesn't hurt to include the /tmp dir for all platforms.
      - type: bind
        source: /tmp
        target: /tmp
    depends_on:
      - redis
      - config
    working_dir: /app
    command: [ "node", "--inspect=0.0.0.0:9229", "app.js" ]
  #/bot_manager


  #custom_reports: A service for custom reports.
  custom_reports:
    image: node
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
    volumes:
      - type: bind
        source: ./developer/custom_reports
        target: /app
      - config:/app/config
    depends_on:
      - redis
      - config
    working_dir: /app
    command: [ "node", "--inspect=0.0.0.0:9229", "app.js" ]
  #/custom_reports

  #definition_manager: (AppBuilder) A service to manage the definitions for a running AppBuilder platform.
  definition_manager:
    image: node
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
    volumes:
      - type: bind
        source: ./developer/definition_manager
        target: /app
      - config:/app/config
    depends_on:
      - redis
      - config
    working_dir: /app
    command: [ "node", "--inspect=0.0.0.0:9229", "app.js" ]
  #/definition_manager


  #file_processor: A service to manage uploaded files.
  file_processor:
    image: node
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
    volumes:
      - type: bind
        source: ./developer/file_processor
        target: /app
      - config:/app/config
      - files:/data
    depends_on:
      - redis
      - config
    working_dir: /app
    command: [ "node", "--inspect=0.0.0.0:9229", "app.js" ]
  #/file_processor


  #log_manager: (AppBuilder) A log manager for various AB operations
  log_manager:
    image: node
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
    volumes:
      - type: bind
        source: ./developer/log_manager
        target: /app
      - config:/app/config
    depends_on:
      - redis
      - config
    working_dir: /app
    command: [ "node", "--inspect=0.0.0.0:9229", "app.js" ]
  #/log_manager


  #notification_email: an smtp email service
  notification_email:
    image: node
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
    volumes:
      - type: bind
        source: ./developer/notification_email
        target: /app
      - config:/app/config
    depends_on:
      - redis
      - config
    working_dir: /app
    command: [ "node", "--inspect=0.0.0.0:9229", "app.js" ]
  #/notification_email


  #process_manager: (AppBuilder) a micro service to manage our process tasks
  process_manager:
    image: node
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
    volumes:
      - type: bind
        source: ./developer/process_manager
        target: /app
      - config:/app/config
    depends_on:
      - redis
      - config
    working_dir: /app
    command: [ "node", "--inspect=0.0.0.0:9229", "app.js" ]
  #/process_manager


  #relay: (Appbuilder} A service to handle the communications with our relay server.
  relay:
    image: node
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
    hostname: relay
    volumes:
      - type: bind
        source: ./developer/relay
        target: /app
      - config:/app/config
    depends_on:
      - redis
      - config
    working_dir: /app
    command: [ "node", "--inspect=0.0.0.0:9229", "app.js" ]
  #/relay


  #tenant_manager: (AppBuilder) A service to manage the site's tenants
  tenant_manager:
    image: node
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
    volumes:
      - type: bind
        source: ./developer/tenant_manager
        target: /app
      - config:/app/config
    depends_on:
      - redis
      - config
    working_dir: /app
    command: [ "node", "--inspect=0.0.0.0:9229", "app.js" ]
  #/tenant_manager


  #user_manager: (AppBuilder) A microservice for managing Users
  user_manager:
    image: node
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
    volumes:
      - type: bind
        source: ./developer/user_manager
        target: /app
      - config:/app/config
    depends_on:
      - redis
      - config
    working_dir: /app
    command: [ "node", "--inspect=0.0.0.0:9229", "app.js" ]
  #/user_manager


#  #watchtower: monitor and update our running containers
#  watchtower:
#    image: v2tec/watchtower
#    volumes:
#      # - /var/run/docker.sock:/var/run/docker.sock
#      - type: bind
#        source: /var/run/docker.sock
#        target: /var/run/docker.sock
#    command: --interval 10 --debug
#  #/watchtower
