version: "3.2"
services:
  #nginx setup
  web:
    image: nginx
    ports:
      - "<%=port%>:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./nginx/html
        target: /usr/share/nginx/html
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./nginx/ssl
        target: /etc/ssl/certs
      - type: bind
        source: ./assets
        target: /data/assets
    depends_on:
      - api_sails
  #/nginx

  #db: use Maria DB as our backend DB
  db:
    image: mariadb
    ports:
      - "<%=portDB%>:3306"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /secret/password
    volumes:
      - type: bind
        source: ./mysql/conf.d/my.cnf
        target: /etc/mysql/conf.d/my.cnf
      - type: bind
        source: ./mysql/init
        target: /docker-entrypoint-initdb.d
      - type: bind
        source: ./mysql/data
        target: /var/lib/mysql
      # - type: bind
      #   source: ./mysql/conf.d
      #   target: /etc/mysql/conf.d
      - type: bind
        source: ./mysql/key
        target: /key
      - type: bind
        source: ./mysql/password
        target: /secret/password
    # on windows: use this command. (be sure to clear out mysql/data folder)
    # command: mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON
  #/db

  #redis: use redis to allow cote services to find each other across a swarm
  redis:
    image: redis
    #ports:
    #  - 6379:6379
    volumes:
      - type: bind
        source: ./redis/data
        target: /data
    command: redis-server --appendonly yes
  #/redis

  #api_sails: our API end point
  api_sails:
    image: node
    # ports:
    #   - "9229:9229"
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
    volumes:
      - type: bind
        source: ./config/local.js
        target: /app/config/local.js
      - type: bind
        source: ./developer/api_sails
        target: /app
      - type: bind
        source: ./data
        target: /data
    depends_on:
      - redis
    working_dir: /app
    command: npm run dev
  #/api_sails

  #bot_manager: our #slack bot service
  bot_manager:
    image: node
    # ports:
    #   - "1338:1338"
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
    volumes:
      - type: bind
        source: ./developer/bot_manager
        target: /app
      - type: bind
        source: ./config/local.js
        target: /app/config/local.js
      # sharing .sock files currently don't work on docker-for-mac:
      # https://github.com/docker/for-mac/issues/483
      # For a Mac host, configure config/local.js to hostConnection.tcp
      # but it doesn't hurt to include the /tmp dir for all platforms.
      - type: bind
        source: /tmp
        target: /tmp
    depends_on:
      - redis
    working_dir: /app
    command: npm run dev
  #/bot_manager

  #notification_email: an smtp email service
  notification_email:
    image: node
    # ports:
    #   - "9229:9229"
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
    volumes:
      - type: bind
        source: ./developer/notification_email
        target: /app
      - type: bind
        source: ./config/local.js
        target: /app/config/local.js
    depends_on:
      - redis
    working_dir: /app
    command: npm run dev
  #/notification_email

#  #watchtower: monitor and update our running containers
#  watchtower:
#    image: v2tec/watchtower
#    volumes:
#      # - /var/run/docker.sock:/var/run/docker.sock
#      - type: bind
#        source: /var/run/docker.sock
#        target: /var/run/docker.sock
#    command: --interval 10 --debug
#  #/watchtower


  #file_processor: A service to manage uploaded files.
  file_processor:
    image: node
    # ports:
    #   - "9229:9229"
    environment:
      - COTE_DISCOVERY_REDIS_HOST=redis
    volumes:
      - type: bind
        source: ./developer/file_processor
        target: /app
      - type: bind
        source: ./config/local.js
        target: /app/config/local.js
      - type: bind
        source: ./data
        target: /data
    depends_on:
      - redis
    working_dir: /app
    command: npm run dev
  #/file_processor
