version: "3.9"
volumes:
  mysql_config:
  mysql_data:
  mysql_key:
  mysql_password:

networks:
  default:
    attachable: true

services:
  #db: use Maria DB as our backend DB
  db:
    image: mariadb
    ports:
      - "<%=dbPort%>:3306"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /secret/password
    volumes:
      #
      # Pull In our local ./mysql/init files to initialize the DB
      #
      - type: bind
        source: ./mysql/init
        target: /docker-entrypoint-initdb.d
      #
      # Now use our volumes 
      # (previously configured by config-compose.yml)
      #
      - mysql_config:/etc/mysql/conf.d
      - mysql_data:/var/lib/mysql
      - mysql_key:/key
      - mysql_password:/secret
    # on windows: use this command. (be sure to clear out mysql/data folder)
    # command: mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON
  #/db