version: "3.2"
services:
  #nginx setup
  web:
    image: nginx
    ports:
      - "<%=port%>:80"
      - "443:443"
    volumes:
      - type: bind
        source: ./nginx/html
        target: /usr/share/nginx/html
      - type: bind
        source: ./assets
        target: /data/assets
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./nginx/ssl
        target: /etc/ssl/certs
    depends_on:
      - apiSails
  #/nginx

  #apiSails: our API end point
  apiSails:
    image: skipdaddy/ab-api-sails:<%=tag%>
    # ports:
    #   - "9229:9229"
    volumes:
      - type: bind
        source: ./config/local.js
        target: /app/config/local.js
  #/apiSails

  #bot_manager: our #slack bot service
  botManager:
    image: skipdaddy/ab-bot-manager:<%=tag%>
    # ports:
    #   - "9229:9229"
    volumes:
      - type: bind
        source: ./config/local.js
        target: /app/config/local.js
      # sharing .sock files currently don't work on docker-for-mac:
      # https://github.com/docker/for-mac/issues/483
      # For a Mac host, configure config/local.js to hostConnection.tcp
      # but it doesn't hurt to include the /tmp dir for all platforms.
      - type: bind
        source: /tmp
        target: /tmp
  #/bot_manager

  #notification_email: an smtp email service
  notificationEmail:
    image: skipdaddy/ab-notification-email:<%=tag%>
    # ports:
    #   - "9229:9229"
    volumes:
      - type: bind
        source: ./config/local.js
        target: /app/config/local.js
      # TODO: if we enable passing of file paths for attachments
      # we'll need to include the common /data directory as well
  #/notification_email


#  #watchtower: monitor and update our running containers
#  watchtower:
#    image: v2tec/watchtower
#    volumes:
#      # - /var/run/docker.sock:/var/run/docker.sock
#      - type: bind
#        source: /var/run/docker.sock
#        target: /var/run/docker.sock
#    command: --interval 10 --debug
#  #/watchtower
