#
# config-compose.yml
# this stack will initialize our data volumes with the various current 
# configuration files of our install.

version: "3.9"
volumes:
  config:
  mysql_config:
  mysql_key:
  mysql_password:
  nginx_etc:
services:

  #config: simply exists to pull in the config/local.js into our config volume
  config:
    image: <%=configImage%>
    environment:
      - AB_CONFIG_INSTALL=true
    volumes:
<%=configBind%>
      ##
      ## mount our local config Files:
      ##
      - type: bind
        source: ./config/local.js
        target: /config_safe/local.js
      - type: bind
        source: ./mysql/conf.d/my-noencrypt.cnf
        target: /mysql_config_source/my.cnf
      - type: bind
        source: ./mysql/key
        target: /mysql_key_source
      - type: bind
        source: ./mysql/password
        target: /mysql_password_source/password
      - type: bind
        source: ./nginx/nginx.conf
        target: /nginx/nginx.conf
      - type: bind
        source: ./nginx/default-nossl.conf
        target: /nginx/conf.d/default.conf
      - type: bind
        source: ./nginx/ssl
        target: /ssl

      ##
      ## Mount our Volumes to update
      ##
      - config:/config
      - mysql_config:/mysql_config
      - mysql_key:/mysql_key
      - mysql_password:/mysql_password
      - nginx_etc:/nginx_etc
    working_dir: /app
    command: ["node", "app.js"]
  #/config
