name: E2E Tests
on:
   # Run on any commit to the #master branch
   push:
      branches: [master]
   # Run on pull requests into the #master branch
   pull_request:
      branches: [master]
   # Allows user to trigger the workflow from GitHub's web UI
   workflow_dispatch:

jobs:
   cypress-test:
      name: Run Tests
      runs-on: ubuntu-latest
      steps:
         - name: Install AppBuilder
           uses: digi-serve/ab-install-action@v1
           with:
              folder: ab
              port: 8080
              runtime: ${{ github.sha }}

         - name: Check out kitchen-sink tests
           uses: actions/checkout@v2
           with:
              repository: digi-serve/kitchensink_app
              path: ab/test/e2e/cypress/integration/kitchensink_app
              
         # Docker's daemon couldn't find the network "ab_default" so the services aren't created
         - name: Restart Docker
           run: sudo systemctl restart docker

         - name: Deploy Stack
           run: ./UP.sh -t -q
           working-directory: ./ab

         - name: Run Cypress Tests
           uses: cypress-io/github-action@v2
           with:
              working-directory: ./ab
              project: ./test/e2e
              config: baseUrl=http://localhost:8080,responseTimeout=100000,defaultCommandTimeout=24000,retries=2
              wait-on: "http://localhost:8080"
              wait-on-timeout: 300
              install: false
              env: stack=ab
